services:
  prometheus-nvidiasmi:
    image: quay.io/genevera/prometheus-nvidiasmi:latest
    build:
      context: .
      dockerfile: Dockerfile
    # environment:
    #   - TEST_MODE=1
    ports:
      - 9202:9202/tcp
    gpus: all
    tty: true
    volumes:
      - ./src/app.go:/go/app.go
      - ./nvidia-smi.sample.xml:/go/nvidia-smi.sample.xml:ro
